# Generated by Django 5.1.3 on 2024-12-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0002_alter_asistencia_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistencia',
            field=models.BooleanField(),
        ),
    ]
