# Generated by Django 5.1.3 on 2024-12-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0003_alter_asistencia_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='deuda_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
