# Generated by Django 5.1.3 on 2024-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0004_prestamo_activo_prestamo_deuda_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='detalle',
            field=models.JSONField(default=list),
        ),
    ]
