# Generated by Django 5.1.3 on 2024-12-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0005_pago_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='activo',
            new_name='estatus',
        ),
    ]
