# Generated by Django 5.1.3 on 2024-12-05 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0006_rename_activo_prestamo_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='abono',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='abono',
            name='deuda_restante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
